# Generated by Django 5.2.7 on 2025-11-03 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_progress_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='join_date',
            field=models.DateField(auto_now_add=True, verbose_name='Join date'),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('user', 'challenge')},
        ),
    ]
